### ISSUE TITLE
undefined method `color' for "2 vulnerable gems found

### ISSUE THREAD

**Issue by digitalfrost** [mackuba/holepicker#17]
Just installed and tried to run holepicker as per the README instructions got this error:

```
holepicker my_app
Fetching list of vulnerabilities...
Looking for gemfiles...
/home/sam/code/my_app/Gemfile.lock: /home/sam/.rvm/gems/ruby-2.0.0-p353/gems/holepicker-0.3.1/lib/holepicker/logger.rb:23:in `fail': undefined method `color' for "2 vulnerable gems found!":String (NoMethodError)
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/gems/holepicker-0.3.1/lib/holepicker/scanner.rb:77:in `scan_gemfile'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/gems/holepicker-0.3.1/lib/holepicker/scanner.rb:58:in `block in scan_path'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/gems/holepicker-0.3.1/lib/holepicker/scanner.rb:58:in `each'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/gems/holepicker-0.3.1/lib/holepicker/scanner.rb:58:in `scan_path'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/gems/holepicker-0.3.1/lib/holepicker/scanner.rb:42:in `block in scan'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/gems/holepicker-0.3.1/lib/holepicker/scanner.rb:42:in `each'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/gems/holepicker-0.3.1/lib/holepicker/scanner.rb:42:in `scan'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/gems/holepicker-0.3.1/bin/holepicker:64:in `<top (required)>'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/bin/holepicker:23:in `load'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/bin/holepicker:23:in `<main>'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
    from /home/sam/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by mackuba** [comment]
Ah, it's @sickill's fault, apparently he changed the API in the `rainbow` gem :) For now just install the 1.x version manually.

**Comment by digitalfrost** [comment]
Thanks - that worked great as a quick fix

**Comment by ku1ik** [comment]
No, it's @jsuder's fault :P You have too weak version specification in gemspec.

**Comment by mhenrixon** [comment]
:+1:
