### ISSUE TITLE
Can't handle gems with platform in version

### ISSUE THREAD

**Issue by bct** [mackuba/holepicker#3]
When I run holepicker against this minimal Gemfile.lock: 

```
GEM
  remote: https://rubygems.org/
  specs:
    win32console (1.3.2-x86-mingw32)

PLATFORMS
  x86-mingw32

DEPENDENCIES
  win32console
```

I get:

```
/home/bct/src/test/Gemfile.lock: /home/bct/.rbenv/versions/1.9.3-p374/lib/ruby/1.9.1/rubygems/version.rb:187:in `initialize': Malformed version number string 1.3.2-x86-mingw32 (ArgumentError)
from /home/bct/.rbenv/versions/1.9.3-p374/lib/ruby/gems/1.9.1/gems/holepicker-0.1.1/lib/holepicker/gem.rb:14:in `new'
```

**Comment by MrJoy** [comment]
This is a problem for me as well.  "1.7.3-java" as a version causes it to choke.

**Comment by mackuba** [comment]
Thanks for reporting, this should work now.
